### ISSUE TITLE
Groups works incorrect

### ISSUE THREAD

**Issue by roxblnfk** [yiisoft/router-fastroute#12]
### What steps will reproduce the problem?
Add into [RouterFactory](https://github.com/yiisoft/yii-demo/blob/474fcab5be0fcf6762cefd68c80f3dcfdc1d01ae/src/Factory/AppRouterFactory.php)
```php
        $router = (new RouterFactory(new FastRouteFactory(), $routes))($container);
        $router->addGroup('/blog', static function (RouteCollectorInterface $r) use (&$container) {
            $r->addRoute(
                Route::get('/index')
                     ->to(new ActionCaller(SiteController::class, 'index', $container))
                     ->name('blog/index')
            );
        });
        return $router;
```
Go to `/blog/index`

### What is the expected result?
Response with HTTP 200 and index page

### What do you get instead?
Response with HTTP 405

### Additional info

Works strange with next code:
```php
$router->addGroup('/blog', ... $r->addRoute(Route::get('/') ...) # /blog/
```
Performs as path `/`

**Comment by rustamwin** [comment]
Related to yiisoft/router#16
