### ISSUE TITLE
Remove not substituted arguments

### ISSUE THREAD

**Issue by g-rodigy** [yiisoft/router-fastroute#133]
Proposal to not add not substituted arguments if they a not in route.  I think this not need here, in `UrlGenerator::generate()` has the separate argument for query string. If it ok, I can make PR.
https://github.com/yiisoft/router-fastroute/blob/2a570aa9d99743bee69faf34c9b712b6d7dd2941/src/UrlGenerator.php#L300-L303

### What steps will reproduce the problem?
````php
// routes
Route::get('/view/{mode}')->name('view');
````
````php
$urlGenerator->setDefaultParameter('mode', 'simple');
$urlGenerator->setDefaultParameter('type', 'any');

$urlGenerator->generate('view');
````

### What is the expected result?
/view/simple
### What do you get instead?
/view/simple?type=any

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 3.0.0
| PHP version      | 8.0
| Operating system |

**Comment by samdark** [comment]
Please do. It makes sense.
