### ISSUE TITLE
Unnecessary question mark

### ISSUE THREAD

**Issue by kratkar** [yiisoft/router-fastroute#134]
### What steps will reproduce the problem?
`Route::get('/articles')->name('article')`

`$urlGenerator->generate('article', [], ['query' => null])`

### What is the expected result?
`/articles`

### What do you get instead?
`/articles?`
'?' at the end url

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 3.0.?
| PHP version      | 8.0
| Operating system | Linux

**Comment by samdark** [comment]
Thanks for reporting. That definitely shouldn't generate `?` for URLs without parameters.

**Comment by samdark** [comment]
Do you have time for a fix?
