### ISSUE TITLE
Use interface for cache instead of using FS directly

### ISSUE THREAD

**Issue by xepozz** [yiisoft/router-fastroute#8]

**Comment by Nex-Otaku** [comment]
@xepozz this issue is resolved?

**Comment by xepozz** [comment]
I don't think so because we have our own implementation for [file cache](https://github.com/yiisoft/router-fastroute/blob/master/src/FastRouteCache.php#L20).
It looks superfluous.

**Comment by xepozz** [comment]
I want to abandon [FastRouteCache](https://github.com/yiisoft/router-fastroute/blob/master/src/FastRouteCache.php) in favor of specialized packages that implement PSR interface. 
If anyone wants to use file cache he can do `composer req yiisoft/cache-file` and add some lines to config.

**Comment by yiiliveext** [comment]
> I want to abandon [FastRouteCache](https://github.com/yiisoft/router-fastroute/blob/master/src/FastRouteCache.php) in favor of specialized packages that implement PSR interface.
> If anyone wants to use file cache he can do `composer req yiisoft/cache-file` and add some lines to config.

It will be removed. This was a temoprary solution.
