### ISSUE TITLE
Allow URL matcher to match static routes

### ISSUE THREAD

**Issue by vjik** [yiisoft/router-fastroute#88]
For example, `Route::get('/i/{image}')->name('image')`.

**Comment by samdark** [comment]
Why can't it match now?

**Comment by vjik** [comment]
Static routes are ignored.
https://github.com/yiisoft/router-fastroute/blob/38258dab2c1d1d5d67ea3fa014a38aa257833a18/src/UrlMatcher.php#L203

**Comment by samdark** [comment]
What would happen after a match?

**Comment by samdark** [comment]
It makes no sense to match this type of routes since these are "generation-only". Let's close this issue as "by design".
