### ISSUE TITLE
UrlGenerator::generate and UrlGenerate::generateAbsolute with nested $parameters arguments.

### ISSUE THREAD

**Issue by Gerych1984** [yiisoft/router-fastroute#95]
Good day. After last releases methods `generate` and `generateAbsolute` was failed on that string ` $parameters = array_map('\strval', $parameters);` if send multilevel array like this (generated from Yiisoft\Form\FormModel attributes)
```
[
    'Search' => [
        'address.with_data' => false
        'address.objects.type_ids' => [
            0 => '4'
        ]
        'address.objects.is_active' => true
        'address.pageData.page.source_ids' => [
            0 => '6'
        ]
    ]
]
```

**Comment by vjik** [comment]
Why use multi-dimensional arrays as parameters?
Value of parameters should be string or type that can be cast to a string.

**Comment by Gerych1984** [comment]
> Why use multi-dimensional arrays as parameters? Value of parameters should be string or type that can be cast to a string.

Ok, but how append/send custom querystring?

**Comment by vjik** [comment]
Seems, this is bug. Previous parameters casting to string in `http_build_query()`.

**Comment by vjik** [comment]
We will resolve this problem by fix https://github.com/yiisoft/router/issues/158
